# Generated by Django 5.2.9 on 2025-12-11 11:48

import openwisp_modem_upgrader.base.models
import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modem_upgrader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modemfirmwareimage",
            name="file",
            field=private_storage.fields.PrivateFileField(
                max_length=255,
                storage=private_storage.storage.files.PrivateFileSystemStorage(
                    base_url="/modem-firmware/"
                ),
                upload_to=openwisp_modem_upgrader.base.models.get_modem_build_directory,
                verbose_name="File",
            ),
        ),
    ]
