# Generated by Django 5.2.8 on 2026-03-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modem_upgrader", "0003_default_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modemfirmwareimage",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("telit-fn990axx-v1", "Telit FN990AXX")],
                help_text="Modem firmware image type: model or manufacturer. ",
                max_length=128,
            ),
        ),
    ]
